import Link from 'next/link';

export const metadata = {
  title: 'Disclaimer & Terms of Use — Alpha-Trade Engine',
};

export default function DisclaimerPage() {
  return (
    <main className="min-h-screen bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-50 p-6">
      <div className="max-w-3xl mx-auto space-y-6">
        <div className="flex items-center justify-between border-b border-slate-200 dark:border-slate-800 pb-4">
          <h1 className="text-2xl font-bold tracking-tight text-emerald-600 dark:text-emerald-400">
            Disclaimer &amp; Terms of Use
          </h1>
          <Link href="/dashboard" className="text-xs text-slate-600 dark:text-slate-400 hover:text-emerald-600 dark:hover:text-emerald-400 underline">
            ← Back to dashboard
          </Link>
        </div>

        <div className="space-y-5 text-sm leading-relaxed text-slate-700 dark:text-slate-300">
          <section>
            <h2 className="font-semibold text-slate-900 dark:text-slate-100 mb-1.5">1. Not financial advice</h2>
            <p>
              Alpha-Trade Engine (&ldquo;the platform&rdquo;) is an educational and practice tool. Nothing on this
              site — including trading signals, AI-generated news explanations, company reports, sector/broker
              recommendations, or the assistant chat — constitutes financial, investment, tax, or legal advice, or
              a recommendation or solicitation to buy, sell, or hold any security, cryptocurrency, or other asset.
              You should not rely on any content here as the basis for a real-world financial decision.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-slate-900 dark:text-slate-100 mb-1.5">2. Simulated trading only</h2>
            <p>
              All trading on the platform is simulated using fake currency in a practice portfolio. No real money,
              securities, or assets are ever transacted through this platform, and it is not a broker-dealer,
              exchange, or investment adviser. Simulated performance does not represent, and is not indicative of,
              results you would achieve trading real capital.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-slate-900 dark:text-slate-100 mb-1.5">3. No warranty on data or AI-generated content</h2>
            <p>
              Market data is sourced from free, delayed, third-party feeds and may be inaccurate, incomplete, or
              stale. Technical signals are produced by a rules-based engine, not a licensed analyst. News
              explanations, reports, and chat responses may be generated by AI and can be wrong, outdated, or
              entirely fabricated (&ldquo;hallucinated&rdquo;), even when phrased confidently. Nothing on the
              platform is verified by a financial professional before being shown to you. Everything is provided
              &ldquo;as is&rdquo; and &ldquo;as available,&rdquo; without warranty of any kind, express or implied.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-slate-900 dark:text-slate-100 mb-1.5">4. Your responsibility</h2>
            <p>
              Any decision you make with real money — whether or not it was informed by something you saw on this
              platform — is made entirely at your own discretion and risk. Trading and investing involve substantial
              risk of loss and are not suitable for everyone. You are solely responsible for evaluating the merits
              and risks of any real-world financial decision and, if appropriate, should consult a licensed
              financial, tax, or legal professional before acting.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-slate-900 dark:text-slate-100 mb-1.5">5. Limitation of liability</h2>
            <p>
              To the fullest extent permitted by law, the operator of this platform disclaims all liability for
              any loss, damage, or unsuccessful trading or investment outcome — direct, indirect, incidental, or
              consequential — arising from or related to your use of the platform, your reliance on any
              information presented on it, or any real-world financial decision you make in connection with it.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-slate-900 dark:text-slate-100 mb-1.5">6. AI Guide chatbot access is non-refundable</h2>
            <p>
              Unlocking the AI Guide chat is a one-time $5 payment. All sales are final — payments for AI Guide
              chatbot access are non-refundable, for any reason, once made. Please make sure you want access before
              paying.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-slate-900 dark:text-slate-100 mb-1.5">7. Acceptance</h2>
            <p>
              By creating an account, you confirm that you have read, understood, and agree to this disclaimer.
              If you do not agree, do not create an account or use the platform.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
