import type { Metadata } from 'next';
import Link from 'next/link';
export const metadata: Metadata = { title: 'Privacy policy', description: 'What Alpha-Trade Engine collects, how data is used, and how to download or delete your account.' };
export default function Privacy() {
  const contact = process.env.NEXT_PUBLIC_PRIVACY_CONTACT_EMAIL;
  return <main className="mx-auto max-w-3xl space-y-8 px-4 py-12 leading-7">
    <header><h1 className="text-3xl font-semibold">Privacy policy</h1><p className="mt-2 text-sm text-slate-600 dark:text-slate-400">Updated October 6, 2026</p></header>
    <section><h2 className="text-xl font-semibold">Information collected</h2><p>Alpha-Trade Engine stores your email address, password hash, account security settings, sessions and terms acceptance. Optional information includes your profile and picture, trading preferences, simulated portfolios and trades, saved analyses, broker account details and Telegram connection. Payment status and a Stripe payment reference are stored; card details are handled by Stripe.</p></section>
    <section><h2 className="text-xl font-semibold">How information is used</h2><p>Information supports sign-in, account protection, personalized research, simulated trading, requested notifications, payment access and abuse prevention. Avoid entering sensitive personal or financial information into AI prompts. Trading outputs are educational and may be inaccurate.</p></section>
    <section><h2 className="text-xl font-semibold">AI and service providers</h2><p>When you use AI features, your prompt, recent conversation and relevant research context are sent to the selected provider, Google Gemini or OpenAI. Company reports may use Google search grounding. Conversations are not automatically stored in the application database; submitting feedback stores the question and answer with your account, and administrators can review this feedback. Provider processing and retention are governed by their own policies.</p><p className="mt-3">Vercel and Render host the application. An external PostgreSQL service stores account data. Stripe processes payments; Resend sends requested emails; Telegram delivers notifications if connected. Market requests use Yahoo Finance and Binance. These providers may process network information and operational logs. The operator has not published the database provider identity or backup retention period here.</p></section>
    <section><h2 className="text-xl font-semibold">Storage and retention</h2><p>An HttpOnly cookie keeps you signed in. Browser storage remembers preferences such as theme and dismissed notices. Profile pictures are stored with your profile, are not published in a public upload bucket, and remain until replaced, removed or your account is deleted. A daily cleanup removes feedback older than 30 days and security sessions, tokens and quota records more than one day past expiry. Scheduled cleanup can be delayed when the API service is unavailable.</p><p className="mt-3">Other account records remain while your account exists. Account deletion removes active database records and ends your sessions. Independently held payment records, provider logs and backups may remain under their retention policies; deletion does not imply immediate removal from backups.</p></section>
    <section><h2 className="text-xl font-semibold">Download and deletion</h2><p>In <Link href="/settings" className="underline">Settings</Link>, download your account records, remove your picture or permanently delete your account. Export and deletion require your password and an authenticator or recovery code if enabled. Deletion also removes your paid chat entitlement. Chat access uses a one-time payment, not an automatically renewing subscription.</p></section>
    <section><h2 className="text-xl font-semibold">Privacy enquiries</h2>{contact ? <p>Contact <a className="underline" href={`mailto:${contact}`}>{contact}</a> for questions about your information.</p> : <p>A dedicated privacy contact has not yet been published. Account downloads and deletion are available directly in Settings. Operator contact details and any jurisdiction-specific notices still need to be supplied.</p>}</section>
  </main>;
}
